param (
    [string]$BasePath = "c:\Dev\agente-core"
)

$ErrorActionPreference = "Continue"

$indexesPath = Join-Path $BasePath "00-governance\indexes"
if (-not (Test-Path $indexesPath)) {
    New-Item -ItemType Directory -Path $indexesPath -Force | Out-Null
}

function Generate-GlobalIndex {
    $dirs = Get-ChildItem -Path $BasePath -Directory | Where-Object { $_.Name -match "^(0[0-9]|1[0-7])-" }
    $content = "# Global Architecture Index`n`n"
    $content += "This index is auto-generated by the auto-doc-generator.ps1 tool.`n`n"
    foreach ($d in $dirs) {
        $content += "## $($d.Name)`n"
        $readmePath = Join-Path $d.FullName "README.md"
        if (Test-Path $readmePath) {
            $content += "- [README](../$($d.Name)/README.md)`n"
            $content += "- [ARCHITECTURE](../$($d.Name)/ARCHITECTURE.md)`n"
        }
        $content += "`n"
    }
    Set-Content -Path (Join-Path $indexesPath "global-index.md") -Value $content -Encoding UTF8
}

function Generate-SemanticTree {
    $content = "# Semantic Architecture Tree`n`n"
    $content += "```txt`n"
    $dirs = Get-ChildItem -Path $BasePath -Directory | Where-Object { $_.Name -match "^(0[0-9]|1[0-7])-" }
    foreach ($d in $dirs) {
        $content += "+-- $($d.Name)/`n"
        $subdirs = Get-ChildItem -Path $d.FullName -Directory
        foreach ($sd in $subdirs) {
            $content += "|   +-- $($sd.Name)/`n"
        }
    }
    $content += "````n"
    Set-Content -Path (Join-Path $indexesPath "semantic-tree.md") -Value $content -Encoding UTF8
}

function Generate-SkillIndex {
    $skillsPath = Join-Path $BasePath "09-skills"
    if (-not (Test-Path $skillsPath)) { return }
    $content = "# Skill Taxonomy Index`n`n"
    $categories = Get-ChildItem -Path $skillsPath -Directory
    foreach ($cat in $categories) {
        $content += "## $($cat.Name)`n"
        $skills = Get-ChildItem -Path $cat.FullName -Directory
        foreach ($s in $skills) {
            $content += "- $($s.Name)`n"
        }
        $content += "`n"
    }
    Set-Content -Path (Join-Path $indexesPath "skill-index.md") -Value $content -Encoding UTF8
}

Set-Content -Path (Join-Path $indexesPath "domain-index.md") -Value "# Domain Index`n`nTODO: Auto-generate domain mappings." -Encoding UTF8
Set-Content -Path (Join-Path $indexesPath "agent-index.md") -Value "# Agent Index`n`nTODO: Auto-generate agent list from 03-agent-system." -Encoding UTF8
Set-Content -Path (Join-Path $indexesPath "workflow-index.md") -Value "# Workflow Index`n`nTODO: Auto-generate workflows from 04-workflows." -Encoding UTF8

Generate-GlobalIndex
Generate-SemanticTree
Generate-SkillIndex

Write-Output "Documentation and indexes generated successfully."
